application: hogbaytaskpaper
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /favicon.ico
  static_files: www/favicon.ico
  upload: www/favicon.ico

- url: /documents
  script: documents.py

- url: /documents/
  script: documents.py

- url: /v1/.*
  script: documents.py
 
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  
- url: /documents
  static_dir: www/com.hogbaysoftware.documents.Documents
