application: hogbaywriteroom
version: 2
runtime: python
api_version: 1

handlers:

- url: /
  static_files: www/index_writeroom.html
  upload: www/index_writeroom.html

- url: /favicon.ico
  static_files: www/favicon_writeroom.ico
  upload: www/favicon_writeroom.ico

- url: /header.png
  static_files: www/header_writeroom.png
  upload: www/header_writeroom.png

- url: /admin
  script: documents.py

- url: /documents
  script: documents.py

- url: /documents/
  script: documents.py

- url: /documents
  static_dir: www/war
    
- url: /v1/.*
  script: documents.py