application: hogbaytaskpaper
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: www/index_taskpaper.html
  upload: www/index_taskpaper.html

- url: /favicon.ico
  static_files: www/favicon_taskpaper.ico
  upload: www/favicon_taskpaper.ico

- url: /header.png
  static_files: www/header_taskpaper.png
  upload: www/header_taskpaper.png

- url: /admin
  script: documents.py

- url: /documents
  script: documents.py

- url: /documents/
  script: documents.py

- url: /documents
  static_dir: www/war
    
- url: /v1/.*
  script: documents.py